import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { useEffect, useState } from 'react';
import {
    Alert,
    FlatList,
    Platform,
    SafeAreaView,
    Share,
    StyleSheet,
    Text,
    TouchableOpacity,
    View,
} from 'react-native';
import { ActivityIndicator } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useTheme } from '../context/ThemeContext';
import { fetchReports } from '../services/supabaseClient';

export default function AllReports() {
    const { theme } = useTheme();
    const insets = useSafeAreaInsets();
    const [reports, setReports] = useState([]);
    const [isLoading, setIsLoading] = useState(true);
    const [expandedId, setExpandedId] = useState(null);

    useEffect(() => {
        loadReports();
    }, []);

    const loadReports = async () => {
        try {
            setIsLoading(true);
            const result = await fetchReports();
            if (!result.success) throw new Error('Could not load reports.');
            setReports(result.data || []);
        } catch (err) {
            Alert.alert('Error', err.message);
        } finally {
            setIsLoading(false);
        }
    };

    const parseJSON = (field) => {
        if (!field) return [];
        if (typeof field === 'string') {
            try { return JSON.parse(field); } catch { return []; }
        }
        return field;
    };

    const fmtDate = (d) => new Date(d).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' });
    const fmtTime = (d) => new Date(d).toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' });

    const scoreColor = (s) => s >= 80 ? '#16a34a' : s >= 60 ? '#d97706' : s >= 40 ? '#ea580c' : '#dc2626';
    const scoreLabel = (s) => s >= 80 ? 'Excellent' : s >= 60 ? 'Good' : s >= 40 ? 'Fair' : 'Needs Work';

    const handleShare = async (r) => {
        const str = parseJSON(r.strengths).map(s => `  • ${s}`).join('\n');
        const wk = parseJSON(r.weaknesses).map(w => `  • ${w}`).join('\n');
        const sg = parseJSON(r.suggestions).map(s => `  • ${s}`).join('\n');

        const text =
`🧘 YogaSathi Daily Report
📅 ${fmtDate(r.created_at)}
📊 Score: ${r.score}/100 (${scoreLabel(r.score)})

📝 Summary: ${r.summary}

✅ Strengths:\n${str}
⚠️ Areas to Improve:\n${wk}
💡 Suggestions:\n${sg}

— Generated by YogaSathi AI`;

        try {
            await Share.share({ message: text, title: `YogaSathi Report - ${fmtDate(r.created_at)}` });
        } catch {
            Alert.alert('Error', 'Could not share the report.');
        }
    };

    const handleDownloadPDF = async (r, dayNum) => {
        const strengths = parseJSON(r.strengths);
        const weaknesses = parseJSON(r.weaknesses);
        const suggestions = parseJSON(r.suggestions);
        const sc = scoreColor(r.score);

        const html = `
        <html>
        <head>
            <meta charset="utf-8" />
            <style>
                * { margin: 0; padding: 0; box-sizing: border-box; }
                body { font-family: 'Helvetica Neue', Arial, sans-serif; padding: 40px; color: #333; background: #fff; }
                .header { text-align: center; padding-bottom: 25px; border-bottom: 3px solid #2e7d32; margin-bottom: 30px; }
                .header h1 { color: #2e7d32; font-size: 28px; margin-bottom: 4px; }
                .header p { color: #888; font-size: 14px; }
                .meta-row { display: flex; justify-content: space-between; align-items: center; margin-bottom: 25px; }
                .day-badge { background: #e8f5e9; color: #2e7d32; padding: 6px 16px; border-radius: 20px; font-weight: 700; font-size: 14px; }
                .date-text { color: #666; font-size: 14px; }
                .score-card { text-align: center; background: #f8faf8; border-radius: 16px; padding: 25px; margin-bottom: 25px; border: 1px solid #e0e0e0; }
                .score-value { font-size: 64px; font-weight: 800; color: ${sc}; }
                .score-max { font-size: 24px; color: #999; font-weight: 400; }
                .score-label { display: inline-block; margin-top: 8px; padding: 4px 14px; border-radius: 12px; font-size: 14px; font-weight: 600; color: ${sc}; background: ${sc}18; }
                .summary { background: #fafafa; border-left: 4px solid #2e7d32; padding: 16px 20px; margin-bottom: 25px; border-radius: 0 8px 8px 0; font-style: italic; line-height: 1.6; color: #555; font-size: 14px; }
                .section { margin-bottom: 22px; }
                .section-title { font-size: 16px; font-weight: 700; margin-bottom: 10px; display: flex; align-items: center; }
                .section-title .icon { width: 20px; height: 20px; border-radius: 10px; display: inline-block; margin-right: 8px; }
                .green { background: #dcfce7; color: #16a34a; }
                .amber { background: #fef3c7; color: #d97706; }
                .blue { background: #e0f2fe; color: #0284c7; }
                .section ul { list-style: none; padding: 0; }
                .section li { padding: 8px 12px; margin-bottom: 6px; border-radius: 8px; background: #f5f5f5; font-size: 14px; line-height: 1.5; }
                .footer { text-align: center; margin-top: 40px; padding-top: 20px; border-top: 1px solid #eee; color: #aaa; font-size: 12px; }
            </style>
        </head>
        <body>
            <div class="header">
                <h1>🧘 YogaSathi</h1>
                <p>AI Wellness Companion — Daily Report</p>
            </div>
            <div class="meta-row">
                <span class="day-badge">Day ${dayNum}</span>
                <span class="date-text">${fmtDate(r.created_at)} at ${fmtTime(r.created_at)}</span>
            </div>
            <div class="score-card">
                <span class="score-value">${r.score}</span><span class="score-max">/100</span>
                <br/>
                <span class="score-label">${scoreLabel(r.score)}</span>
            </div>
            <div class="summary">${r.summary}</div>
            ${strengths.length > 0 ? `
            <div class="section">
                <div class="section-title"><span class="icon green"></span> Strengths</div>
                <ul>${strengths.map(s => `<li>✅ ${s}</li>`).join('')}</ul>
            </div>` : ''}
            ${weaknesses.length > 0 ? `
            <div class="section">
                <div class="section-title"><span class="icon amber"></span> Areas to Improve</div>
                <ul>${weaknesses.map(w => `<li>⚠️ ${w}</li>`).join('')}</ul>
            </div>` : ''}
            ${suggestions.length > 0 ? `
            <div class="section">
                <div class="section-title"><span class="icon blue"></span> Suggestions for Tomorrow</div>
                <ul>${suggestions.map(s => `<li>💡 ${s}</li>`).join('')}</ul>
            </div>` : ''}
            <div class="footer">Generated by YogaSathi AI • ${fmtDate(r.created_at)}</div>
        </body>
        </html>`;

        try {
            const { uri } = await Print.printToFileAsync({ html, base64: false });
            await Sharing.shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf' });
        } catch (err) {
            Alert.alert('Error', 'Could not generate PDF. Please try again.');
        }
    };

    const renderCard = ({ item, index }) => {
        const isOpen = expandedId === item.id;
        const sc = scoreColor(item.score);
        const strengths = parseJSON(item.strengths);
        const weaknesses = parseJSON(item.weaknesses);
        const suggestions = parseJSON(item.suggestions);

        return (
            <TouchableOpacity
                style={[styles.card, { backgroundColor: theme.card, borderColor: theme.border }]}
                onPress={() => setExpandedId(isOpen ? null : item.id)}
                activeOpacity={0.85}
            >
                <View style={styles.cardHeader}>
                    <View style={styles.cardHeaderLeft}>
                        <View style={[styles.dayBadge, { backgroundColor: theme.accent }]}>
                            <Text style={[styles.dayBadgeText, { color: theme.primary }]}>Day {reports.length - index}</Text>
                        </View>
                        <View>
                            <Text style={[styles.cardDate, { color: theme.text }]}>{fmtDate(item.created_at)}</Text>
                            <Text style={[styles.cardTime, { color: theme.textMuted }]}>{fmtTime(item.created_at)}</Text>
                        </View>
                    </View>
                    <View style={styles.scoreSection}>
                        <Text style={[styles.scoreValue, { color: sc }]}>{item.score}</Text>
                        <Text style={[styles.scoreMax, { color: theme.textMuted }]}>/100</Text>
                    </View>
                </View>

                <View style={[styles.scoreLabelRow, { borderTopColor: theme.divider }]}>
                    <View style={[styles.scoreLabelBadge, { backgroundColor: sc + '18' }]}>
                        <View style={[styles.scoreLabelDot, { backgroundColor: sc }]} />
                        <Text style={[styles.scoreLabelText, { color: sc }]}>{scoreLabel(item.score)}</Text>
                    </View>
                    <View style={styles.cardActions}>
                        <TouchableOpacity
                            style={[styles.actionBtn, { backgroundColor: '#e0f2fe' }]}
                            onPress={() => handleDownloadPDF(item, reports.length - index)}
                        >
                            <Ionicons name="download-outline" size={18} color="#0284c7" />
                        </TouchableOpacity>
                        <TouchableOpacity
                            style={[styles.actionBtn, { backgroundColor: theme.accent }]}
                            onPress={() => handleShare(item)}
                        >
                            <Ionicons name="share-outline" size={18} color={theme.primary} />
                        </TouchableOpacity>
                        <Ionicons name={isOpen ? 'chevron-up' : 'chevron-down'} size={20} color={theme.textMuted} />
                    </View>
                </View>

                {isOpen && (
                    <View style={[styles.expandedContent, { borderTopColor: theme.divider }]}>
                        <Text style={[styles.summaryText, { color: theme.textSecondary }]}>{item.summary}</Text>

                        {strengths.length > 0 && (
                            <View style={styles.detailSection}>
                                <View style={styles.detailTitleRow}>
                                    <Ionicons name="checkmark-circle" size={16} color="#16a34a" />
                                    <Text style={[styles.detailTitle, { color: theme.text }]}> Strengths</Text>
                                </View>
                                {strengths.map((s, i) => (
                                    <Text key={`s-${i}`} style={[styles.detailItem, { color: theme.textSecondary }]}>{s}</Text>
                                ))}
                            </View>
                        )}

                        {weaknesses.length > 0 && (
                            <View style={styles.detailSection}>
                                <View style={styles.detailTitleRow}>
                                    <Ionicons name="alert-circle" size={16} color="#d97706" />
                                    <Text style={[styles.detailTitle, { color: theme.text }]}> Areas to Improve</Text>
                                </View>
                                {weaknesses.map((w, i) => (
                                    <Text key={`w-${i}`} style={[styles.detailItem, { color: theme.textSecondary }]}>{w}</Text>
                                ))}
                            </View>
                        )}

                        {suggestions.length > 0 && (
                            <View style={styles.detailSection}>
                                <View style={styles.detailTitleRow}>
                                    <Ionicons name="bulb" size={16} color="#0284c7" />
                                    <Text style={[styles.detailTitle, { color: theme.text }]}> Suggestions</Text>
                                </View>
                                {suggestions.map((sg, i) => (
                                    <Text key={`sg-${i}`} style={[styles.detailItem, { color: theme.textSecondary }]}>{sg}</Text>
                                ))}
                            </View>
                        )}
                    </View>
                )}
            </TouchableOpacity>
        );
    };

    return (
        <SafeAreaView style={[styles.safeArea, { backgroundColor: theme.background }]}>
            <View style={[styles.header, { paddingTop: Platform.OS === 'android' ? insets.top + 10 : 10 }]}>
                <TouchableOpacity onPress={() => router.back()} style={styles.backBtn}>
                    <Ionicons name="arrow-back" size={24} color={theme.text} />
                </TouchableOpacity>
                <Text style={[styles.headerTitle, { color: theme.text }]}>My Reports</Text>
                <View style={{ width: 24 }} />
            </View>

            {isLoading ? (
                <View style={styles.centerBox}>
                    <ActivityIndicator size="large" color={theme.primary} />
                    <Text style={[styles.loadingText, { color: theme.textSecondary }]}>Loading reports...</Text>
                </View>
            ) : reports.length === 0 ? (
                <View style={styles.centerBox}>
                    <Ionicons name="document-text-outline" size={64} color={theme.textMuted} />
                    <Text style={[styles.emptyTitle, { color: theme.text }]}>No Reports Yet</Text>
                    <Text style={[styles.emptySubtitle, { color: theme.textSecondary }]}>
                        Complete your daily reflection to generate your first AI report.
                    </Text>
                    <TouchableOpacity style={[styles.ctaBtn, { backgroundColor: theme.primary }]} onPress={() => router.push('/reflection')}>
                        <Text style={styles.ctaBtnText}>Start Reflection</Text>
                    </TouchableOpacity>
                </View>
            ) : (
                <FlatList
                    data={reports}
                    keyExtractor={(item) => item.id}
                    renderItem={renderCard}
                    contentContainerStyle={styles.listContent}
                    showsVerticalScrollIndicator={false}
                />
            )}
        </SafeAreaView>
    );
}

const styles = StyleSheet.create({
    safeArea: { flex: 1 },
    header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 20, paddingBottom: 15 },
    backBtn: { padding: 5 },
    headerTitle: { fontSize: 20, fontWeight: 'bold' },
    centerBox: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 30 },
    loadingText: { marginTop: 12, fontSize: 15 },
    emptyTitle: { fontSize: 22, fontWeight: 'bold', marginTop: 18, marginBottom: 8 },
    emptySubtitle: { fontSize: 15, textAlign: 'center', lineHeight: 22, marginBottom: 25 },
    ctaBtn: { borderRadius: 28, paddingVertical: 14, paddingHorizontal: 30 },
    ctaBtnText: { color: '#fff', fontSize: 16, fontWeight: '600' },
    listContent: { paddingHorizontal: 20, paddingBottom: 40 },
    card: { borderRadius: 16, borderWidth: 1, marginBottom: 14, overflow: 'hidden' },
    cardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 16 },
    cardHeaderLeft: { flexDirection: 'row', alignItems: 'center' },
    dayBadge: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 8, marginRight: 12 },
    dayBadgeText: { fontSize: 13, fontWeight: '700' },
    cardDate: { fontSize: 15, fontWeight: '600' },
    cardTime: { fontSize: 12, marginTop: 2 },
    scoreSection: { flexDirection: 'row', alignItems: 'baseline' },
    scoreValue: { fontSize: 28, fontWeight: '800' },
    scoreMax: { fontSize: 14, fontWeight: '500', marginLeft: 2 },
    scoreLabelRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 10, borderTopWidth: 1 },
    scoreLabelBadge: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12 },
    scoreLabelDot: { width: 8, height: 8, borderRadius: 4, marginRight: 6 },
    scoreLabelText: { fontSize: 13, fontWeight: '600' },
    cardActions: { flexDirection: 'row', alignItems: 'center', gap: 10 },
    actionBtn: { width: 36, height: 36, borderRadius: 18, justifyContent: 'center', alignItems: 'center' },
    expandedContent: { padding: 16, borderTopWidth: 1 },
    summaryText: { fontSize: 14, lineHeight: 22, fontStyle: 'italic', marginBottom: 14 },
    detailSection: { marginBottom: 14 },
    detailTitleRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 8 },
    detailTitle: { fontSize: 15, fontWeight: '700' },
    detailItem: { fontSize: 14, lineHeight: 22, paddingLeft: 8, marginBottom: 4 },
});
